/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmsDrive;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import hmsDrive.Reser;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author PCB
 */
public final class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    public int num;

    ArrayList<Reser> reserList = new ArrayList<>();  // 어레이 리스트 생성

    public String getKey() {  // 선택한 열의 전화번호 가져오는 함수
        String key = null;
        DefaultTableModel model = (DefaultTableModel) reserTable.getModel();
        int row = reserTable.getSelectedRow();  // reserTable에서 선택한 열 값
        key = (String) model.getValueAt(row, 3);  // 전화번호 

        return key;
    }

    public Reservation() { 
        initComponents();
        reserList();  // 테이블에 예약 리스트 넣는 함수
        setArr();  // 텍스트 파일 구분자로 잘라서 어레이리스트에 넣는 함수 
    }

    public Reservation(int num) {
        this.num = num;
        initComponents();
    }

    // 텍스트 파일 구분자(/)로 잘라서 어레이리스트에 넣기
    public void setArr() {

        reserList.clear();  // 어레이리스트 클리어

        try {
            //읽을 파일 열기
            BufferedReader br = new BufferedReader(new FileReader("Reser.txt"));

            String line = "";
            String[] str = null;

            while ((line = br.readLine()) != null) {  // 더 이상 읽을 데이터가 없을 때 까지 
                str = line.split("/");  // 구분자(/)로 데이터 자르기  
                reserList.add(new Reser(str[0], str[1], str[2], str[3], str[4], str[5], str[6], str[7], str[8]));  // 어레이리스트에 데이터 넣기 
            }

            br.close();  // 파일 닫기
            
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }

    // 테이블에 예약 리스트 넣기
    public void reserList() {

        String[] key;
        String line = "";
        try {
            DefaultTableModel table = (DefaultTableModel) reserTable.getModel();

            BufferedReader br = new BufferedReader(new FileReader("Reser.txt"));

            while ((line = br.readLine()) != null) {  // 읽을 데이터가 없을 때 까지
                key = line.split("/");  // 구분자(/)로 데이터 자르기 
                Object[] list = {key[0], key[1], key[2], key[3], key[4], key[5], key[6], key[7], key[8]};  // 예약 번호, 객실번호, 이름, 전화번호, 인원 수, 예상 체크인 날짜, 예상 체크인 시간, 예상 체크아웃 날짜. 예상 체크아웃 시간
                table.addRow(list);  // 테이블에 리스트 넣기 
            }
            br.close();

        } catch (FileNotFoundException e) {
            System.out.println(e);
        } catch (IOException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_add = new javax.swing.JDialog();
        add = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        roomNum = new javax.swing.JTextField();
        phoneNum = new javax.swing.JTextField();
        peopleNum = new javax.swing.JTextField();
        expCheckinDate = new javax.swing.JTextField();
        expCheckinTime = new javax.swing.JTextField();
        expCheckoutDate = new javax.swing.JTextField();
        expCheckoutTime = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jDialog_search = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        sCH = new javax.swing.JButton();
        sDEL = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reserSearchTable = new javax.swing.JTable();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jDialog_change = new javax.swing.JDialog();
        change = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cRoomNum = new javax.swing.JTextField();
        cPhoneNum = new javax.swing.JTextField();
        cPeopleNum = new javax.swing.JTextField();
        cExpCheckinDate = new javax.swing.JTextField();
        cExpCheckinTime = new javax.swing.JTextField();
        cExpCheckoutDate = new javax.swing.JTextField();
        cExpCheckoutTime = new javax.swing.JTextField();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jDialog_searchCh = new javax.swing.JDialog();
        schange = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        scName = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        scRoomNum = new javax.swing.JTextField();
        scPhoneNum = new javax.swing.JTextField();
        scPeopleNum = new javax.swing.JTextField();
        scExpCheckinDate = new javax.swing.JTextField();
        scExpCheckinTime = new javax.swing.JTextField();
        scExpCheckoutDate = new javax.swing.JTextField();
        scExpCheckoutTime = new javax.swing.JTextField();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButt_SEARCH = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        searchPhoneNum = new javax.swing.JTextField();
        jButt_CHANGE = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        reserTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jDialog_add.setMinimumSize(new java.awt.Dimension(400, 570));
        jDialog_add.setModal(true);
        jDialog_add.setResizable(false);

        add.setText("예약추가");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel8.setText("고객 이름 :");

        jLabel9.setText("전화번호 :");

        jLabel10.setText("인원 수 :");

        jLabel11.setText("예상 체크인 날짜 :");

        jLabel7.setText("객실 번호 :");

        jLabel12.setText("예상 체크인 시간 :");

        jLabel13.setText("예상 체크아웃 날짜 :");

        jLabel14.setText("예상 체크아웃 시간 :");

        jLabel15.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel15.setText("예약 추가");

        jMenu2.setText("메뉴");

        jMenuItem3.setText("창 닫기");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar2.add(jMenu2);

        jDialog_add.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jDialog_addLayout = new javax.swing.GroupLayout(jDialog_add.getContentPane());
        jDialog_add.getContentPane().setLayout(jDialog_addLayout);
        jDialog_addLayout.setHorizontalGroup(
            jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_addLayout.createSequentialGroup()
                .addGroup(jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialog_addLayout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addGap(18, 18, 18)
                            .addGroup(jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(roomNum)
                                .addComponent(name)
                                .addComponent(phoneNum)
                                .addComponent(peopleNum)
                                .addComponent(expCheckinDate)
                                .addComponent(expCheckinTime)
                                .addComponent(expCheckoutDate)
                                .addComponent(expCheckoutTime, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                        .addGroup(jDialog_addLayout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jLabel15))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jDialog_addLayout.setVerticalGroup(
            jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_addLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(23, 23, 23)
                .addGroup(jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(roomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(peopleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(expCheckinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(expCheckinTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(expCheckoutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(expCheckoutTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jDialog_search.setMinimumSize(new java.awt.Dimension(900, 350));
        jDialog_search.setModal(true);
        jDialog_search.setResizable(false);
        jDialog_search.setSize(new java.awt.Dimension(1125, 290));

        jLabel16.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel16.setText("예약 검색 결과");
        jLabel16.setToolTipText("");

        sCH.setText("수정");
        sCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCHActionPerformed(evt);
            }
        });

        sDEL.setText("삭제");
        sDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sDELActionPerformed(evt);
            }
        });

        jButton6.setText("종료");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        reserSearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "예약 번호", "객실 번호", "이름", "전화번호", "인원 수", "예상 체크인 날짜", "예상 체크인 시간", "예상 체크아웃 날짜", "예상 체크아웃 시간"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reserSearchTable);

        jMenu3.setText("메뉴");

        jMenuItem4.setText("창닫기");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar3.add(jMenu3);

        jDialog_search.setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout jDialog_searchLayout = new javax.swing.GroupLayout(jDialog_search.getContentPane());
        jDialog_search.getContentPane().setLayout(jDialog_searchLayout);
        jDialog_searchLayout.setHorizontalGroup(
            jDialog_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_searchLayout.createSequentialGroup()
                .addGroup(jDialog_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_searchLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jLabel16))
                    .addGroup(jDialog_searchLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(sCH, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog_searchLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jDialog_searchLayout.setVerticalGroup(
            jDialog_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_searchLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jDialog_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sCH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jDialog_change.setMinimumSize(new java.awt.Dimension(400, 570));
        jDialog_change.setModal(true);
        jDialog_change.setResizable(false);

        change.setText("예약수정");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        jLabel17.setText("고객 이름 :");

        jLabel18.setText("전화번호 :");

        jLabel19.setText("인원 수 :");

        jLabel20.setText("예상 체크인 날짜 :");

        jLabel21.setText("객실 번호 :");

        jLabel22.setText("예상 체크인 시간 :");

        jLabel23.setText("예상 체크아웃 날짜 :");

        jLabel24.setText("예상 체크아웃 시간 :");

        jLabel25.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel25.setText("예약 수정");

        jMenu4.setText("메뉴");

        jMenuItem5.setText("창 닫기");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar4.add(jMenu4);

        jDialog_change.setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout jDialog_changeLayout = new javax.swing.GroupLayout(jDialog_change.getContentPane());
        jDialog_change.getContentPane().setLayout(jDialog_changeLayout);
        jDialog_changeLayout.setHorizontalGroup(
            jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_changeLayout.createSequentialGroup()
                .addGroup(jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialog_changeLayout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel17)
                                .addComponent(jLabel21)
                                .addComponent(jLabel18)
                                .addComponent(jLabel20)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24))
                            .addGap(18, 18, 18)
                            .addGroup(jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cRoomNum)
                                .addComponent(cName)
                                .addComponent(cPhoneNum)
                                .addComponent(cPeopleNum)
                                .addComponent(cExpCheckinDate)
                                .addComponent(cExpCheckinTime)
                                .addComponent(cExpCheckoutDate)
                                .addComponent(cExpCheckoutTime, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                        .addGroup(jDialog_changeLayout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jLabel25))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jDialog_changeLayout.setVerticalGroup(
            jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_changeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(23, 23, 23)
                .addGroup(jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cRoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cPeopleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cExpCheckinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cExpCheckinTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cExpCheckoutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cExpCheckoutTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jDialog_searchCh.setMinimumSize(new java.awt.Dimension(400, 570));
        jDialog_searchCh.setModal(true);
        jDialog_searchCh.setResizable(false);

        schange.setText("예약수정");
        schange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schangeActionPerformed(evt);
            }
        });

        jLabel26.setText("고객 이름 :");

        jLabel27.setText("전화번호 :");

        jLabel28.setText("인원 수 :");

        jLabel29.setText("예상 체크인 날짜 :");

        jLabel30.setText("객실 번호 :");

        jLabel31.setText("예상 체크인 시간 :");

        jLabel32.setText("예상 체크아웃 날짜 :");

        jLabel33.setText("예상 체크아웃 시간 :");

        jLabel34.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel34.setText("예약 수정");

        jMenu5.setText("메뉴");

        jMenuItem6.setText("창 닫기");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar5.add(jMenu5);

        jDialog_searchCh.setJMenuBar(jMenuBar5);

        javax.swing.GroupLayout jDialog_searchChLayout = new javax.swing.GroupLayout(jDialog_searchCh.getContentPane());
        jDialog_searchCh.getContentPane().setLayout(jDialog_searchChLayout);
        jDialog_searchChLayout.setHorizontalGroup(
            jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_searchChLayout.createSequentialGroup()
                .addGroup(jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(schange, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialog_searchChLayout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel28)
                                .addComponent(jLabel26)
                                .addComponent(jLabel30)
                                .addComponent(jLabel27)
                                .addComponent(jLabel29)
                                .addComponent(jLabel31)
                                .addComponent(jLabel32)
                                .addComponent(jLabel33))
                            .addGap(18, 18, 18)
                            .addGroup(jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(scRoomNum)
                                .addComponent(scName)
                                .addComponent(scPhoneNum)
                                .addComponent(scPeopleNum)
                                .addComponent(scExpCheckinDate)
                                .addComponent(scExpCheckinTime)
                                .addComponent(scExpCheckoutDate)
                                .addComponent(scExpCheckoutTime, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                        .addGroup(jDialog_searchChLayout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jLabel34))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jDialog_searchChLayout.setVerticalGroup(
            jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_searchChLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(23, 23, 23)
                .addGroup(jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(scRoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(scName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(scPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(scPeopleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(scExpCheckinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(scExpCheckinTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(scExpCheckoutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_searchChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(scExpCheckoutTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(schange, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel1.setText("예약시스템");

        jLabel2.setText("예약현황");

        jButt_SEARCH.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        jButt_SEARCH.setText("예약 검색");
        jButt_SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_SEARCHActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        jButton2.setText("예약 추가");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("예약자 전화번호 :");

        jButt_CHANGE.setText("예약 수정");
        jButt_CHANGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_CHANGEActionPerformed(evt);
            }
        });

        delete.setText("예약 삭제");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        reserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "예약 번호", "객실 번호", "이름", "전화번호", "인원 수", "예상 체크인 날짜", "예상 체크인 시간", "예상 체크아웃 날짜", "예상 체크아웃 시간"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(reserTable);

        jMenu1.setText("메뉴");

        jMenuItem1.setText("뒤로가기");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("종료");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(287, 287, 287)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jButt_CHANGE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButt_SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(546, 546, 546)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2)))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButt_CHANGE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButt_SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //상단 메뉴바 뒤로가기 버튼
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        if (num == 1) {
            UserMainMenu umain = new UserMainMenu();
            umain.setVisible(true);
            this.setVisible(false);
        } else if (num == 2) {
            ManagerMainMenu mmain = new ManagerMainMenu();
            mmain.setVisible(true);
            this.setVisible(false);
        } else {
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //상단 메뉴바 종료 버튼
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    //예약 검색 버튼
    private void jButt_SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_SEARCHActionPerformed

        setArr();
        String phoneNum = searchPhoneNum.getText();  // 고객 전화번호 입력받기
        String str = null;

        DefaultTableModel table = (DefaultTableModel) reserSearchTable.getModel();

        table.setNumRows(0);
        for (int i = 0; i < reserList.size(); i++) {
            if (phoneNum.equals(reserList.get(i).getPhoneNum())) {  // 입력받은 전화번호와 에러이리스트의 전화번호가 같은 인덱스  
                Object[] list = {reserList.get(i).getReservationNum(), reserList.get(i).getRoomNum(), reserList.get(i).getName(), reserList.get(i).getPhoneNum(), reserList.get(i).getPeopleNum(), reserList.get(i).getExpCheckinDate(), reserList.get(i).getExpCheckinTime(), reserList.get(i).getExpCheckoutDate(), reserList.get(i).getExpCheckoutTime()};
                table.addRow(list);  // 테이블에 리스트 넣기 
            }
        }

        jDialog_search.setVisible(true);
    }//GEN-LAST:event_jButt_SEARCHActionPerformed

    //예약 추가 버튼
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialog_add.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    //예약 추가 모달창 상단 메뉴바 창닫기 버튼
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jDialog_add.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jDialog_search.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jDialog_search.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    //예약 수정 버튼
    private void jButt_CHANGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_CHANGEActionPerformed

        int row = reserTable.getSelectedRow();  // 선택한 열 값 
        TableModel data = reserTable.getModel();

        // 선택한 값 넣기
        cRoomNum.setText((String) data.getValueAt(row, 1));
        cName.setText((String) data.getValueAt(row, 2));
        cPhoneNum.setText((String) data.getValueAt(row, 3));
        cPeopleNum.setText((String) data.getValueAt(row, 4));
        cExpCheckinDate.setText((String) data.getValueAt(row, 5));
        cExpCheckinTime.setText((String) data.getValueAt(row, 6));
        cExpCheckoutDate.setText((String) data.getValueAt(row, 7));
        cExpCheckoutTime.setText((String) data.getValueAt(row, 8));

        jDialog_change.setVisible(true);
    }//GEN-LAST:event_jButt_CHANGEActionPerformed

    //예약 삭제 버튼
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try {

            setArr();  // 파일 데이테 어레이리스트에 넣기

            String str = null;

            DefaultTableModel model = (DefaultTableModel) reserTable.getModel();
            int row = reserTable.getSelectedRow();  // 선택한 열 값
            String dName = (String) model.getValueAt(row, 2);  // 삭제할 예약의 이름 

            for (int i = 0; i < reserList.size(); i++) {

                // 선택한 열의 이름과 어레이리스트에 있는 이름이 같으면
                if (dName.equals(reserList.get(i).getName())) {
                    reserList.remove(i);  // 삭제
                }
            }

            BufferedWriter bw1 = new BufferedWriter(new OutputStreamWriter(new FileOutputStream("Reser.txt")));
            for (int i = 0; i < reserList.size(); i++) {
                str = String.format("%s/%s/%s/%s/%s/%s/%s/%s/%s%n", reserList.get(i).getReservationNum(), reserList.get(i).getRoomNum(), reserList.get(i).getName(), reserList.get(i).getPhoneNum(), reserList.get(i).getPeopleNum(), reserList.get(i).getExpCheckinDate(), reserList.get(i).getExpCheckinTime(), reserList.get(i).getExpCheckoutDate(), reserList.get(i).getExpCheckoutTime());
                bw1.write(str);  // 텍스트 파일에 넣기
            }
            bw1.close();

            JOptionPane.showMessageDialog(null, "예약 삭제 완료");

            DefaultTableModel table = (DefaultTableModel) reserTable.getModel();
            table.setNumRows(0);  // 테이블 초기화
            reserList();  // 테이블에 예약 리스트 넣기

        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    // 예약 추가 메뉴의 예약 추가 버튼
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        boolean check = true; 

        try {

            // 모든 정보가 입력되지 않으면
            if (roomNum.getText().isEmpty() || name.getText().isEmpty() || phoneNum.getText().isEmpty() || peopleNum.getText().isEmpty() || expCheckinDate.getText().isEmpty() || expCheckinTime.getText().isEmpty() || expCheckoutDate.getText().isEmpty() || expCheckoutTime.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "모든 정보를 입력하세요");
            } else {  
                for (int i = 0; i < reserList.size(); i++) {
                    if (reserList.get(i).getRoomNum().equals(roomNum.getText())) {  // 예약리스트에 있는 객실번호이면
                        check = false;  // check를 false로 변경
                    }
                }

                if (check) {  // check가 true일 때
                    String reservationNum = "0";  // 예약 번호 초기화
                    int a = Integer.parseInt(reserList.get(reserList.size() - 1).getReservationNum()); // 마지막 예약번호 int형으로 변환
                    a++;  // 예약 번호 증가
                    reservationNum = Integer.toString(a);  // string형으로 변환

                    //리스트에 저장
                    reserList.add(new Reser(reservationNum, roomNum.getText(), name.getText(), phoneNum.getText(), peopleNum.getText(), expCheckinDate.getText(), expCheckinTime.getText(), expCheckoutDate.getText(), expCheckoutTime.getText()));
                    BufferedWriter bw;

                    bw = new BufferedWriter(new FileWriter("Reser.txt", true)); // 파일 열기

                    String str = null;

                    str = String.format("%s/%s/%s/%s/%s/%s/%s/%s/%s%n", reservationNum, roomNum.getText(), name.getText(), phoneNum.getText(), peopleNum.getText(), expCheckinDate.getText(), expCheckinTime.getText(), expCheckoutDate.getText(), expCheckoutTime.getText());
                    bw.write(str);  // 파일에 넣기
                    bw.close();  // 파일 닫기
                    setArr();  // 파일 데이테 어레이리스트에 넣기

                    // 초기화
                    roomNum.setText("");
                    name.setText("");
                    phoneNum.setText("");
                    peopleNum.setText("");
                    expCheckinDate.setText("");
                    expCheckinTime.setText("");
                    expCheckoutDate.setText("");
                    expCheckoutTime.setText("");

                    JOptionPane.showMessageDialog(null, "예약 추가 완료");

                    DefaultTableModel table = (DefaultTableModel) reserTable.getModel();
                    table.setNumRows(0);
                    reserList();
                    
                } else {  // check가 false이면
                    JOptionPane.showMessageDialog(null, "이미 예약된 객실입니다. 다시 입력하세요.");
                }
            }
            roomNum.setText("");
            name.setText("");
            phoneNum.setText("");
            peopleNum.setText("");
            expCheckinDate.setText("");
            expCheckinTime.setText("");
            expCheckoutDate.setText("");
            expCheckoutTime.setText("");
        } catch (IOException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_addActionPerformed

    // 예약 변경 버튼
    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        
        // 입력된 값 불러오기
        String roomNum = cRoomNum.getText();
        String name = cName.getText();
        String phoneNum = cPhoneNum.getText();
        String peopleNum = cPeopleNum.getText();
        String expCheckinDate = cExpCheckinDate.getText();
        String expCheckinTime = cExpCheckinTime.getText();
        String expCheckoutDate = cExpCheckoutDate.getText();
        String expCheckoutTime = cExpCheckoutTime.getText();

        String str = null;
        String key = getKey(); // 선택한 열의 전화번호 가져옴
        FileOutputStream file;

        
        try {
            // 모든 정보를 입력하지 않았을 때
            if (cRoomNum.getText().isEmpty() || cName.getText().isEmpty() || cPhoneNum.getText().isEmpty() || cPeopleNum.getText().isEmpty() || cExpCheckinDate.getText().isEmpty() || cExpCheckinTime.getText().isEmpty() || cExpCheckoutDate.getText().isEmpty() || cExpCheckoutTime.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "모든 정보를 입력하세요");
            } else {  

                setArr();  // 파일 데이터 어레이 리스트에 넣기

                file = new FileOutputStream("Reser.txt");
                BufferedWriter bw = new BufferedWriter(new FileWriter("Reser.txt"));

                for (int i = 0; i < reserList.size(); i++) {  

                    if (key.equals(reserList.get(i).getPhoneNum())) {  // 선택한 열의 전화번호와 어레이리스트의 전화번호가 같으면
                        // 같은 인덱스 정보들 변경
                        reserList.get(i).setRoomNum(roomNum); 
                        reserList.get(i).setName(name);
                        reserList.get(i).setPhoneNum(phoneNum);
                        reserList.get(i).setPeopleNum(peopleNum);
                        reserList.get(i).setExpCheckinDate(expCheckinDate);
                        reserList.get(i).setExpCheckinTime(expCheckinTime);
                        reserList.get(i).setExpCheckoutDate(expCheckoutDate);
                        reserList.get(i).setExpCheckoutTime(expCheckoutTime);
                    }
                    str = String.format("%s/%s/%s/%s/%s/%s/%s/%s/%s%n", reserList.get(i).getReservationNum(), reserList.get(i).getRoomNum(), reserList.get(i).getName(), reserList.get(i).getPhoneNum(), reserList.get(i).getPeopleNum(), reserList.get(i).getExpCheckinDate(), reserList.get(i).getExpCheckinTime(), reserList.get(i).getExpCheckoutDate(), reserList.get(i).getExpCheckoutTime());
                    bw.write(str);
                }
                bw.close();

                // 초기화
                cRoomNum.setText("");
                cName.setText("");
                cPhoneNum.setText("");
                cPeopleNum.setText("");
                cExpCheckinDate.setText("");
                cExpCheckinTime.setText("");
                cExpCheckoutDate.setText("");
                cExpCheckoutTime.setText("");

                JOptionPane.showMessageDialog(null, "예약 수정 완료");
                DefaultTableModel table = (DefaultTableModel) reserTable.getModel();
                
                // 테이블 업데이트
                table.setNumRows(0); // 테이블 지우기
                reserList();  // 테이블 값 넣기 
            }

        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_changeActionPerformed


    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    // 예약 검색 결과 수정 들어가는 버튼
    private void sCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCHActionPerformed
       
        DefaultTableModel data = (DefaultTableModel) reserSearchTable.getModel();
        int row = reserSearchTable.getSelectedRow();  // 클릭한 열 

        // 예약 수정에서 선택한 라인의 값 넣기
        cRoomNum.setText((String) data.getValueAt(row, 1));
        cName.setText((String) data.getValueAt(row, 2));
        cPhoneNum.setText((String) data.getValueAt(row, 3));
        cPeopleNum.setText((String) data.getValueAt(row, 4));
        cExpCheckinDate.setText((String) data.getValueAt(row, 5));
        cExpCheckinTime.setText((String) data.getValueAt(row, 6));
        cExpCheckoutDate.setText((String) data.getValueAt(row, 7));
        cExpCheckoutTime.setText((String) data.getValueAt(row, 8));

        jDialog_change.setVisible(true);
    }//GEN-LAST:event_sCHActionPerformed

    // 예약 검색 결과 삭제 
    private void sDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sDELActionPerformed

        try {

            setArr();  // 파일 데이테 어레이리스트에 넣기

            String str = null;  

            DefaultTableModel model = (DefaultTableModel) reserSearchTable.getModel();
            int row = reserSearchTable.getSelectedRow();  // 선택한 열 값
            String dPhoneNum = (String) model.getValueAt(row, 3);  // 삭제할 예약의 전화번호

            for (int i = 0; i < reserList.size(); i++) {

                // 선택한 열의 이름과 어레이리스트에 있는 이름이 같으면
                if (dPhoneNum.equals(reserList.get(i).getPhoneNum())) {
                    reserList.remove(i);  // 삭제
                }
            }
            
            BufferedWriter bw1 = new BufferedWriter(new OutputStreamWriter(new FileOutputStream("Reser.txt")));
            for (int i = 0; i < reserList.size(); i++) {
                str = String.format("%s/%s/%s/%s/%s/%s/%s/%s/%s%n", reserList.get(i).getReservationNum(), reserList.get(i).getRoomNum(), reserList.get(i).getName(), reserList.get(i).getPhoneNum(), reserList.get(i).getPeopleNum(), reserList.get(i).getExpCheckinDate(), reserList.get(i).getExpCheckinTime(), reserList.get(i).getExpCheckoutDate(), reserList.get(i).getExpCheckoutTime());
                bw1.write(str);  // 파일에 쓰기
            }
            bw1.close();

            JOptionPane.showMessageDialog(null, "예약 삭제 완료");

            DefaultTableModel table = (DefaultTableModel) reserTable.getModel();
            table.setNumRows(0);  // 테이블 초기화
            reserList();  // 테이블에 예약 리스트 넣기

        } catch (IOException ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_sDELActionPerformed

 //검색 결과 변경
    private void schangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schangeActionPerformed

        String scPhoneNum = null;  // 바꿀 전화번호 
        DefaultTableModel model = (DefaultTableModel) reserSearchTable.getModel();  
        int row = reserSearchTable.getSelectedRow();  // 
        scPhoneNum = (String) model.getValueAt(row, 3);  // 전화번호

        String roomNum = cRoomNum.getText();
        String name = cName.getText();
        String phoneNum = cPhoneNum.getText();
        String peopleNum = cPeopleNum.getText();
        String expCheckinDate = cExpCheckinDate.getText();
        String expCheckinTime = cExpCheckinTime.getText();
        String expCheckoutDate = cExpCheckoutDate.getText();
        String expCheckoutTime = cExpCheckoutTime.getText();

        String str = null;

        FileOutputStream file;

        try {
            setArr();  // 파일 데이터 어레이 리스트에 넣기
            file = new FileOutputStream("Reser.txt");

            // 입력받는 정보가 하나라도 비어있으면 다시 입력받기
            if (cRoomNum.getText().isEmpty() || cName.getText().isEmpty() || cPhoneNum.getText().isEmpty() || cPeopleNum.getText().isEmpty() || cExpCheckinDate.getText().isEmpty() || cExpCheckinTime.getText().isEmpty() || cExpCheckoutDate.getText().isEmpty() || cExpCheckoutTime.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "모든 정보를 입력하세요");

            } else {  // 모든 정보가 입력 되어있으면 

                for (int i = 0; i < reserList.size(); i++) {

                    if (scPhoneNum.equals(reserList.get(i).getPhoneNum())) {  // 바꿀 전화번호와 어레이리스트의 전화번호가 같은 값이 들어있는 인덱스 i 
                        
                        // 값 변경
                        reserList.get(i).setRoomNum(roomNum);
                        reserList.get(i).setName(name);
                        reserList.get(i).setPhoneNum(phoneNum);
                        reserList.get(i).setPeopleNum(peopleNum);
                        reserList.get(i).setExpCheckinDate(expCheckinDate);
                        reserList.get(i).setExpCheckinTime(expCheckinTime);
                        reserList.get(i).setExpCheckoutDate(expCheckoutDate);
                        reserList.get(i).setExpCheckoutTime(expCheckoutTime);
                    }
                }

                BufferedWriter bw = new BufferedWriter(new FileWriter("Reser.txt"));

                for (int i = 0; i < reserList.size(); i++) {
                    str = String.format("%s/%s/%s/%s/%s/%s/%s/%s/%s%n", reserList.get(i).getReservationNum(), reserList.get(i).getRoomNum(), reserList.get(i).getName(), reserList.get(i).getPhoneNum(), reserList.get(i).getPeopleNum(), reserList.get(i).getExpCheckinDate(), reserList.get(i).getExpCheckinTime(), reserList.get(i).getExpCheckoutDate(), reserList.get(i).getExpCheckoutTime());
                    bw.write(str);  // 파일 쓰기
                }

                bw.close();  // 파일 닫기
            }

        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            System.out.println(ex);
        }

        cRoomNum.setText("");
        cName.setText("");
        cPhoneNum.setText("");
        cPeopleNum.setText("");
        cExpCheckinDate.setText("");
        cExpCheckinTime.setText("");
        cExpCheckoutDate.setText("");
        cExpCheckoutTime.setText("");

        JOptionPane.showMessageDialog(null, "예약 수정 완료");
        DefaultTableModel table = (DefaultTableModel) reserSearchTable.getModel();
        table.setNumRows(0);  // 테이블 초기화 
        reserList();  // 테이블에 값 넣기 


    }//GEN-LAST:event_schangeActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField cExpCheckinDate;
    private javax.swing.JTextField cExpCheckinTime;
    private javax.swing.JTextField cExpCheckoutDate;
    private javax.swing.JTextField cExpCheckoutTime;
    private javax.swing.JTextField cName;
    private javax.swing.JTextField cPeopleNum;
    private javax.swing.JTextField cPhoneNum;
    private javax.swing.JTextField cRoomNum;
    private javax.swing.JButton change;
    private javax.swing.JButton delete;
    private javax.swing.JTextField expCheckinDate;
    private javax.swing.JTextField expCheckinTime;
    private javax.swing.JTextField expCheckoutDate;
    private javax.swing.JTextField expCheckoutTime;
    private javax.swing.JButton jButt_CHANGE;
    private javax.swing.JButton jButt_SEARCH;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog_add;
    private javax.swing.JDialog jDialog_change;
    private javax.swing.JDialog jDialog_search;
    private javax.swing.JDialog jDialog_searchCh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField name;
    private javax.swing.JTextField peopleNum;
    private javax.swing.JTextField phoneNum;
    private javax.swing.JTable reserSearchTable;
    private javax.swing.JTable reserTable;
    private javax.swing.JTextField roomNum;
    private javax.swing.JButton sCH;
    private javax.swing.JButton sDEL;
    private javax.swing.JTextField scExpCheckinDate;
    private javax.swing.JTextField scExpCheckinTime;
    private javax.swing.JTextField scExpCheckoutDate;
    private javax.swing.JTextField scExpCheckoutTime;
    private javax.swing.JTextField scName;
    private javax.swing.JTextField scPeopleNum;
    private javax.swing.JTextField scPhoneNum;
    private javax.swing.JTextField scRoomNum;
    private javax.swing.JButton schange;
    private javax.swing.JTextField searchPhoneNum;
    // End of variables declaration//GEN-END:variables

    private JTextField setValueAt(Object a) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
