

package hms;
import javax.swing.JOptionPane;

/**
 *
 * @author hesed
 */
public class System extends javax.swing.JFrame {

    /**
     * Creates new form System
     */
    public System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Butt_delete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Butt_click1 = new javax.swing.JButton();
        Butt_user = new javax.swing.JButton();
        Butt_back = new javax.swing.JButton();
        Butt_click2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Butt_report = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        text_room = new javax.swing.JTextField();
        text_share = new javax.swing.JTextField();
        text_person = new javax.swing.JTextField();
        text_yield = new javax.swing.JTextField();
        text_cost = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        text_order = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Butt_add = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Butt_change = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Butt_delete.setText("삭제");
        Butt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_deleteActionPerformed(evt);
            }
        });

        jLabel7.setText("주문 내역 :");

        jLabel1.setText("시스템 관리");

        Butt_click1.setText("jButton2");
        Butt_click1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_click1ActionPerformed(evt);
            }
        });

        Butt_user.setText("사용자 관리");
        Butt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_userActionPerformed(evt);
            }
        });

        Butt_back.setText("뒤로가기");
        Butt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_backActionPerformed(evt);
            }
        });

        Butt_click2.setText("jButton2");
        Butt_click2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_click2ActionPerformed(evt);
            }
        });

        jLabel2.setText("예상 점유율 :");

        Butt_report.setText("예외보고서");
        Butt_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_reportActionPerformed(evt);
            }
        });

        jLabel3.setText("수익률 :");

        text_share.setEnabled(false);

        text_yield.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "객실", "사용자", "요금", "주문 내역"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("객실 :");

        Butt_add.setText("추가");
        Butt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_addActionPerformed(evt);
            }
        });

        jLabel5.setText("사용자 :");

        Butt_change.setText("수정");
        Butt_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_changeActionPerformed(evt);
            }
        });

        jLabel6.setText("요금 :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Butt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_share, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Butt_click1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Butt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Butt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(text_yield, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Butt_click2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Butt_report, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_person, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(text_room, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(text_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(text_order, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Butt_change, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Butt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Butt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_share, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Butt_click1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(text_room, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_yield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Butt_click2))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_person, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(13, 13, 13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_order, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Butt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Butt_change, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Butt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Butt_report, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Butt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void Butt_deleteActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if(text_room.getText().isEmpty()){  JOptionPane.showMessageDialog(null, "본인의 룸 번호를 기입해주시기 바랍니다.");}
        else{
            String [] deletemenu = {"사용자", "요금", "주문 내역", "취소"};
            int deletenum = JOptionPane.showOptionDialog(null, text_room.getText() + "호님 어느 것을 삭제하시겠습니까?", null,
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, deletemenu, deletemenu[3]);
            if(deletenum == 0){
                    // 방 번호인 text_room과 같은 줄에 해당하는 데이터베이스의 데이터를 for문으로 방 번호를 찾아서 있으면 data[i]의 i를 다른 변수를 만들어 저장 후 i를 이용해서 찾은 데이터 항목의 내용을 null로 만들것
            
            }
            else if(deletenum == 1){
                 // 방 번호인 text_room과 같은 줄에 해당하는 데이터베이스의 데이터를 for문으로 방 번호를 찾아서 있으면 data[i]의 i를 다른 변수를 만들어 저장 후 i를 이용해서 찾은 데이터 항목의 내용을 null로 만들것
                
            }
            else if(deletenum == 2){
                 // 방 번호인 text_room과 같은 줄에 해당하는 데이터베이스의 데이터를 for문으로 방 번호를 찾아서 있으면 data[i]의 i를 다른 변수를 만들어 저장 후 i를 이용해서 찾은 데이터 항목의 내용을 null로 만들것
                 
            }
            else {}
        }
    }                                           

    private void Butt_click1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        text_share.setText("오른쪽 처럼" + 5);  // 점유율 = 현재 사용되고 있는 방의 개수 나누기 100 한 값이 나오게 설정, 정안되면 계산해서 String으로 해놀고, 데이터베이스 연동 필요
    }                                           

    private void Butt_userActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        new CustomerInfo().setVisible(true);
    }                                         

    private void Butt_backActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        dispose();
    }                                         

    private void Butt_click2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        text_yield.setText("나올수 있게" + 44);  // 수익률 = 현재 지불되어야 되는 가격들 전부 모아서 설정, 데이터베이스 연동 필요
    }                                           

    private void Butt_reportActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        new Report().setVisible(true);
    }                                           

    private void Butt_addActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if(text_room.getText().isEmpty()){  JOptionPane.showMessageDialog(null, "본인의 룸 번호를 기입해주시기 바랍니다.");}
        else{
            String [] changemenu = {"사용자", "요금", "주문 내역", "취소"};
            int addnum = JOptionPane.showOptionDialog(null, text_room.getText() + "호님 어느 것을 추가하시겠습니까?", null,
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, changemenu, changemenu[3]);
            if(addnum == 0){
                   if(text_person.getText() != null){ //이 줄에서 데이터베이스의 사용자가 null이 아닐 경우 나오게 할 것, 적혀있는 조건식은 임의로 적어놨을 뿐 나중에 데이터베이스에 해당하는 걸 통해 찾아내서 확인하게 할 것 
                        JOptionPane.showMessageDialog(null, "추가할 사용자를 적어주시기 바랍니다.");
                   } else{ 
                // 방 번호인 text_room과 같은 줄에 해당하는 데이터베이스의 데이터를 text_person값으로 변경해놓는다. 그 전에 for문으로 방 번호를 찾아서 있으면 data[i]의 i를 다른 변수를 만들어 저장 후 i를 이용해서 넣을 것   
                }
            }
            
            else if(addnum == 1){
                     if(text_cost.getText().isEmpty()){ 
                        JOptionPane.showMessageDialog(null, "추가할 요금을 적어주시기 바랍니다.");
                   } else{ 
                    // 방 번호인 text_room과 같은 줄에 해당하는 데이터베이스의 데이터를 text_cost로 변경해놓는다. 그 전에 for문으로 방 번호를 찾아서 있으면 data[i]의 i를 다른 변수를 만들어 저장 후 i를 이용해서 넣을 것
                } 
        }
            
            else if(addnum == 2){
                    if(text_cost.getText().isEmpty()){ //이 줄에서 데이터베이스의 사용자가 null이 아닐 경우 나오게 할 것, 적혀있는 조건식은 임의로 적어놨을 뿐 나중에 데이터베이스에 해당하는 걸 통해 찾아내서 확인하게 할 것 
                        JOptionPane.showMessageDialog(null, "추가할 주문 내역을 적어주시기 바랍니다.");
                   } else{ 
                     // 방 번호인 text_room과 같은 줄에 해당하는 데이터베이스의 데이터를 text_order 값으로 변경해놓는다. 그 전에 for문으로 방 번호를 찾아서 있으면 data[i]의 i를 다른 변수를 만들어 저장 후 i를 이용해서 넣을 것
                } 
                } else{}
        }
    }                                        

    private void Butt_changeActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if(text_room.getText().isEmpty()){  JOptionPane.showMessageDialog(null, "본인의 룸 번호를 기입해주시기 바랍니다.");}
        else{
            String [] changemenu = {"사용자", "요금", "주문 내역", "취소"};
            int addnum = JOptionPane.showOptionDialog(null, text_room.getText() + "호님 어느 것을 수정하시겠습니까?", null,
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, changemenu, changemenu[3]);
            if(addnum == 0){
                    if(text_person.getText().isEmpty()){  //이 줄에서 데이터베이스의 사용자가 isEmpty일 경우 나오게 할 것, 적혀있는 조건식은 임의로 적어놨을 뿐 나중에 데이터베이스에 해당하는 걸 통해 찾아내서 확인하게 할 것 
                        JOptionPane.showMessageDialog(null, "사용자를 적어주시기 바랍니다.");
                    } 
                    else{
                        // 방 번호인 text_room과 같은 줄에 해당하는 데이터베이스의 데이터를 text_person의 내용으로 변경. 그 전에 for문으로 방 번호를 찾아서 있으면 data[i]의 i를 다른 변수를 만들어 저장 후 i를 이용해서 넣을 것
                    }
            }
            else if(addnum == 1){
                    if(text_cost.getText().isEmpty()){ 
                        JOptionPane.showMessageDialog(null, "요금을 적어주시기 바랍니다.");
                    } 
                    else{
                    // 방 번호인 text_room과 같은 줄에 해당하는 데이터베이스의 데이터를 text_cost의 내용으로 변경, 그 전에 for문으로 방 번호를 찾아서 있으면 data[i]의 i를 다른 변수를 만들어 저장 후 i를 이용해서 넣을 것
                    }
            }
            else if(addnum == 2){
                    if(text_order.getText().isEmpty()){
                        JOptionPane.showMessageDialog(null, "주문 내역을 적어주시기 바랍니다.");
                    } 
                    else{
                    // 방 번호인 text_room과 같은 줄에 해당하는 데이터베이스의 데이터를 text_order의 내용으로 변경해놓는다. 그 전에 for문으로 방 번호를 찾아서 있으면 data[i]의 i를 다른 변수를 만들어 저장 후 i를 이용해서 넣을 것
                }
            }
            else {}
        }
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Butt_add;
    private javax.swing.JButton Butt_back;
    private javax.swing.JButton Butt_change;
    private javax.swing.JButton Butt_click1;
    private javax.swing.JButton Butt_click2;
    private javax.swing.JButton Butt_delete;
    private javax.swing.JButton Butt_report;
    private javax.swing.JButton Butt_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField text_cost;
    private javax.swing.JTextField text_order;
    private javax.swing.JTextField text_person;
    private javax.swing.JTextField text_room;
    private javax.swing.JTextField text_share;
    private javax.swing.JTextField text_yield;
    // End of variables declaration                   
}
